apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 15.6.4
    helm:
      values: |
        auth:
          enabled: true
          rootPassword: rootpass
          database: visits
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: visits
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
